[package]
name = "pdf_extractor"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "pdf_extractor"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.31.0"
extractous = "0.3.0"
